-- ----------------------------
-- Insertions tables de référence
-- ----------------------------

-- especes
INSERT INTO especes (nom, Feuillage) VALUES
  ('Abi', 'Conifère'),
  ('Abicon', 'Conifère'),
  ('Abigla', 'Conifère'),
  ('Abilasari', 'Conifère'),
  ('Abinor', 'Conifère'),
  ('Abinum', 'Conifère'),
  ('Ace', 'Feuillu'),
  ('Acecam', 'Feuillu'),
  ('Acecamele', 'Feuillu'),
  ('Acecamred', 'Feuillu'),
  ('Acecamros', 'Feuillu'),
  ('Acecap', 'Feuillu'),
  ('Acedav', 'Feuillu'),
  ('Aceneg', 'Feuillu'),
  ('Acenegvar', 'Feuillu'),
  ('Acepal', 'Feuillu'),
  ('Acepla', 'Feuillu'),
  ('Aceplacol', 'Feuillu'),
  ('Aceplacri', 'Feuillu'),
  ('Aceplapur', 'Feuillu'),
  ('Acepse', 'Feuillu'),
  ('Acepseatr', 'Feuillu'),
  ('Acepseleo', 'Feuillu'),
  ('Acerub', 'Feuillu'),
  ('Acesac', 'Feuillu'),
  ('Acesacwie', 'Feuillu'),
  ('Aesarnaut', 'Feuillu'),
  ('Aescar', 'Feuillu'),
  ('Aeship', 'Feuillu'),
  ('Aeshom', 'Feuillu'),
  ('Ailalt', 'Feuillu'),
  ('Albjul', 'Feuillu'),
  ('Alncor', 'Feuillu'),
  ('Alnglu', 'Feuillu'),
  ('Alngluimp', 'Feuillu'),
  ('Alnspa', 'Feuillu'),
  ('Amelam', 'Feuillu'),
  ('Betpap', 'Feuillu'),
  ('Betpen', 'Feuillu'),
  ('Betpenyou', 'Feuillu'),
  ('Betuti', 'Feuillu'),
  ('Betutijac', 'Feuillu'),
  ('Buxsem', 'Feuillu'),
  ('Carbet', 'Feuillu'),
  ('Carbetfas', 'Feuillu'),
  ('Cassat', 'Feuillu'),
  ('Catbig', 'Feuillu'),
  ('Catbun', 'Feuillu'),
  ('Cedatl', 'Conifère'),
  ('Cedatlgla', 'Conifère'),
  ('Cedatlpen', 'Conifère'),
  ('Ceddeo', 'Conifère'),
  ('Cedlib', 'Conifère'),
  ('Cersil', 'Feuillu'),
  ('Chalaw', 'Conifère'),
  ('Chanoo', 'Conifère'),
  ('Corave', 'Feuillu'),
  ('Corcol', 'Feuillu'),
  ('Corkou', 'Feuillu'),
  ('Cralaepau', 'Feuillu'),
  ('Cramon', 'Feuillu'),
  ('Cryjap', 'Conifère'),
  ('Cup', 'Conifère'),
  ('Cupari', 'Conifère'),
  ('Cuparigla', 'Conifère'),
  ('Cupfas', 'Conifère'),
  ('Cupley', 'Conifère'),
  ('Cupleyvar', 'Conifère'),
  ('Cupsem', 'Conifère'),
  ('Cydvulbou', 'Feuillu'),
  ('Elaang', 'Feuillu'),
  ('Fagsyl', 'Feuillu'),
  ('Fagsyldawgol', 'Feuillu'),
  ('Fagsyldawpur', 'Feuillu'),
  ('Fagsylfas', 'Feuillu'),
  ('Fagsylfaspur', 'Feuillu'),
  ('Fagsylpen', 'Feuillu'),
  ('Fagsylpur', 'Feuillu'),
  ('Fraame', 'Feuillu'),
  ('Fraang', 'Feuillu'),
  ('Fraangray', 'Feuillu'),
  ('Fraexc', 'Feuillu'),
  ('Fraexcpen', 'Feuillu'),
  ('Fraorn', 'Feuillu'),
  ('Frapencim', 'Feuillu'),
  ('Ginbil', 'Conifère'),
  ('Gletri', 'Feuillu'),
  ('Gletriine', 'Feuillu'),
  ('Gletrisun', 'Feuillu'),
  ('Ileaqu', 'Feuillu'),
  ('Jugreg', 'Feuillu'),
  ('Junmedpfi', 'Conifère'),
  ('Koepan', 'Feuillu'),
  ('Koepanfas', 'Feuillu'),
  ('Labana', 'Feuillu'),
  ('Lagind', 'Feuillu'),
  ('Lardec', 'Conifère'),
  ('Liqsty', 'Feuillu'),
  ('Lirtul', 'Feuillu'),
  ('Maggra', 'Feuillu'),
  ('Magkob', 'Feuillu'),
  ('Magsou', 'Feuillu'),
  ('Magsouhea', 'Feuillu'),
  ('Mal', 'Feuillu'),
  ('Malbac', 'Feuillu'),
  ('Malcom', 'Feuillu'),
  ('Malcomgol', 'Feuillu'),
  ('Malcomtra', 'Feuillu'),
  ('Maldom', 'Feuillu'),
  ('Maldomast', 'Feuillu'),
  ('Maldombel', 'Feuillu'),
  ('Maldombos', 'Feuillu'),
  ('Maldomcal', 'Feuillu'),
  ('Maldomcox', 'Feuillu'),
  ('Maldomgra', 'Feuillu'),
  ('Maldommel', 'Feuillu'),
  ('Maldomrei', 'Feuillu'),
  ('Malgol', 'Feuillu'),
  ('Malpen', 'Feuillu'),
  ('Malpereve', 'Feuillu'),
  ('Malred', 'Feuillu'),
  ('Maltor', 'Feuillu'),
  ('Maltor1', 'Feuillu'),
  ('Maltorbro', 'Feuillu'),
  ('Maltri', 'Feuillu'),
  ('Maltsc', 'Feuillu'),
  ('Metgly', 'Conifère'),
  ('Notant', 'Feuillu'),
  ('Parper', 'Feuillu'),
  ('Pautom', 'Feuillu'),
  ('Picabi', 'Conifère'),
  ('Pinniglar', 'Conifère'),
  ('Pinnignig', 'Conifère'),
  ('Pinsyl', 'Conifère'),
  ('Pinwal', 'Conifère'),
  ('Plaace', 'Feuillu'),
  ('Popalb', 'Feuillu'),
  ('Popcan', 'Feuillu'),
  ('Popeurrob', 'Feuillu'),
  ('Popnig', 'Feuillu'),
  ('Popnigita', 'Feuillu'),
  ('Popsim', 'Feuillu'),
  ('Poptre', 'Feuillu'),
  ('Pru', 'Feuillu'),
  ('Pruavi', 'Feuillu'),
  ('Pruavibea', 'Feuillu'),
  ('Pruavibig', 'Feuillu'),
  ('Pruavimar', 'Feuillu'),
  ('Prucer', 'Feuillu'),
  ('Prucerbig', 'Feuillu'),
  ('Prucerbig1', 'Feuillu'),
  ('Prucerbig2', 'Feuillu'),
  ('Prucercoe', 'Feuillu'),
  ('Prucerpis', 'Feuillu'),
  ('Prudomals', 'Feuillu'),
  ('Prudomcha', 'Feuillu'),
  ('Prudommir', 'Feuillu'),
  ('Prudommon', 'Feuillu'),
  ('Prudomrei', 'Feuillu'),
  ('Prudomrei1', 'Feuillu'),
  ('Prudomrei2', 'Feuillu'),
  ('Prudomrei3', 'Feuillu'),
  ('Prulau', 'Feuillu'),
  ('Prumaaamb', 'Feuillu'),
  ('Prupernuc', 'Feuillu'),
  ('Pruser', 'Feuillu'),
  ('Pruserama', 'Feuillu'),
  ('Pruserfas', 'Feuillu'),
  ('Pruserkan', 'Feuillu'),
  ('Pruserpen', 'Feuillu'),
  ('Prusubaut', 'Feuillu'),
  ('Psemen', 'Conifère'),
  ('Pyrcal', 'Feuillu'),
  ('Pyrcalcha', 'Feuillu'),
  ('Pyrcom', 'Feuillu'),
  ('Pyrcomcon', 'Feuillu'),
  ('Pyrcomdoy', 'Feuillu'),
  ('Quebic', 'Feuillu'),
  ('Quecas', 'Feuillu'),
  ('Quecer', 'Feuillu'),
  ('Quecoc', 'Feuillu'),
  ('Queell', 'Feuillu'),
  ('Queile', 'Feuillu'),
  ('Quemac', 'Feuillu'),
  ('Quepal', 'Feuillu'),
  ('Quepet', 'Feuillu'),
  ('Querob', 'Feuillu'),
  ('Querobfas', 'Feuillu'),
  ('Querub', 'Feuillu'),
  ('Queshu', 'Feuillu'),
  ('Rhutyp', 'Feuillu'),
  ('Robpse', 'Feuillu'),
  ('Salalb', 'Feuillu'),
  ('Salalbche', 'Feuillu'),
  ('Salbab', 'Feuillu'),
  ('Salcap', 'Feuillu'),
  ('Samnig', 'Feuillu'),
  ('Seqgig', 'Conifère'),
  ('Sopjap', 'Feuillu'),
  ('Sopjappen', 'Feuillu'),
  ('Soralb', 'Feuillu'),
  ('Sorari', 'Feuillu'),
  ('Sorarilut', 'Feuillu'),
  ('Sorauc', 'Feuillu'),
  ('Sortor', 'Feuillu'),
  ('Tamgal', 'Feuillu'),
  ('Taxbac', 'Conifère'),
  ('Taxbacfas', 'Conifère'),
  ('Taxdis', 'Conifère'),
  ('Thupli', 'Conifère'),
  ('Thupliatr', 'Conifère'),
  ('Thuplizeb', 'Conifère'),
  ('Tilcor', 'Feuillu'),
  ('Tileur', 'Feuillu'),
  ('Tilhen', 'Feuillu'),
  ('Tilpla', 'Feuillu'),
  ('Tiltom', 'Feuillu'),
  ('Ulmjap', 'Feuillu'),
  ('Ulmmin', 'Feuillu'),
  ('Ulmrebnew', 'Feuillu'),
  ('Ulmres', 'Feuillu'),
  ('Ulmressap', 'Feuillu');

-- stade_dev
INSERT INTO stade_dev (libelle) VALUES
  ('Adulte'),
  ('Jeune'),
  ('Senescent'),
  ('Vieux');

-- quartiers
INSERT INTO quartiers (quartier, secteur) VALUES
  ('Harly', 'Entrée de ville avenue pierre choquart'),
  ('Omissy', 'Chemin de morcourt'),
  ('Quartier de l''europe', 'Avenue buffon'),
  ('Quartier de neuville', 'Centre commercial neuville'),
  ('Quartier du centre-ville', 'Avenue faidherbe'),
  ('Quartier du faubourg d''isle', 'Avenue des fusillés de fontaine notre dame'),
  ('Quartier du vermandois', 'Ancienne ecole david et maigret'),
  ('Quartier remicourt', 'Auberge de jeunesse'),
  ('Quartier saint-jean', 'Accueil de loisirs kergomard'),
  ('Quartier saint-martin - oëstres', 'Avenue du cimetière de la tombelle'),
  ('Rouvroy', 'Entrée de ville rd 300 rouvray');

-- etat
INSERT INTO etat (libelle) VALUES
  ('Abattu'),
  ('En place'),
  ('Essouché'),
  ('Non essouché'),
  ('Remplacé'),
  ('Supprimé');

-- situations
INSERT INTO situations (libelle) VALUES
  ('Alignement'),
  ('Groupe'),
  ('Isolé');

  INSERT INTO arbre (X, Y, haut_tot, haut_tronc, diam_tronc, age_estime, nb_diagnostic, date_plantage, date_abattage, remarquable, id_stade_dev, id_especes, id_etat, id_quartiers, id_situations) VALUES
  (1720057.8587, 8295024.8474, 16.0, 4.0, 148.0, 50, 0, NULL, NULL, 0, 1, 217, 2, 9, 2),
  (1719482.7256, 8295265.287, 5.0, 2.0, 49.0, 20, 0, NULL, NULL, 0, 2, 37, 2, 7, 3),
  (1722294.2737, 8295055.4484, 25.0, 2.0, 250.0, 50, 1, NULL, NULL, 0, 1, 141, 6, 8, 1);